version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: reddit
      POSTGRES_PASSWORD: reddit
      POSTGRES_DB: reddit
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./storage/postgres_schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "5432:5432"

  dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    depends_on:
      - postgres

  streamer:
    build: ./ingestion
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
    
  analyzer:
    build: ./processing
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_started

volumes:
  pg_data:
